[package]
name = "engawa-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = true

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
engawa-server = { path = "../server" }
engawa-shared = { path = "../shared" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
