[package]
name = "engawa-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
categories.workspace = true
keywords = ["chat", "client", "cli", "axum", "websocket"]
description = """
CLI chat client for Engawa, chat application built with Axum and WebSocket.
"""
publish = true

[[bin]]
name = "engawa-client"
path = "src/bin/client.rs"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
engawa-server = { version = "0.0.1", path = "../server" }
engawa-shared = { version = "0.0.1", path = "../shared" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
