[package]
name = "engawa-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
categories.workspace = true
keywords = ["chat", "server", "axum", "websocket"]
description = """
Chat server for Engawa, chat application built with Axum and WebSocket.
"""
publish = true

[[bin]]
name = "engawa-server"
path = "src/bin/server.rs"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
engawa-shared = { version = "0.0.1", path = "../shared" }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
